spring:
  jpa:
    hibernate:
      ddl-auto: update # create update create-update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: ${RDS_URL}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: asdaszxcwqweqweqwe
            client-secret: asddaasdxczxczxcxc
            scope:
              - read:user
              - user:email
          google:
            client-id: dassasddasxcxczxcasd
            client-secret: dasdasdzxczxczxczxc
            scope:
              - email
              - profile
  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_ID}
    password: ${MAIL_PASSWORD}
    port: ${MAIL_PORT}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2

logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secretKey: ${SECURITY_SECRET_KEY}
  refreshKey: ${SECURITY_REFRESH_KEY}

cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}