spring:
  jpa:
    hibernate:
      ddl-auto: update # create update create-update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  datasource:
    url: sadasa
    username: asdadada
    password: adssa
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: asdfas
    port: 22
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: asdaszxcwqweqweqwe
            client-secret: asddaasdxczxczxcxc
            scope:
              - read:user
              - user:email
          google:
            client-id: dassasddasxcxczxcasd
            client-secret: dasdasdzxczxczxczxc
            scope:
              - email
              - profile
  mail:
    host: 12212
    username: asdaas
    password: 1221312
    port: 111
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
            protocols: TLSv1.2

logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.sql: debug
    org.hibernate.type: trace
    org.springframework.security: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

jwt:
  secretKey: sadfsaf
  refreshKey: sfdsfsdfds

cloud:
  aws:
    credentials:
      accessKey: accessKey
      secretKey: secretKey
    s3:
      bucket: bucket
      dir: /image